services:
  # API principal
  qp_backend:
    container_name: qp_backend
    build:
      context: ./app/backend/
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    ports:
      - "4000:4000" # mapea el puerto del host al contenedor
    volumes:
      - ./app/backend:/app # monta el código fuente local dentro del contenedor
      - /app/node_modules # evita conflictos de dependencias
    depends_on:
      - qp_db
    networks:
      - qp_network
    restart: unless-stopped

  # MongoDB
  qp_db:
    image: mongo:7
    container_name: qp-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - mongo_data:/data/db
    networks:
      - qp_network
    restart: unless-stopped

  # frontend
  qp_fronted:
    container_name: qp_fronted
    build:
      context: ./app/frontend/
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    ports:
      - "5173:5173" # mapea el puerto del host al contenedor
    volumes:
      - ./app/frontend:/app # monta el código fuente local dentro del contenedor
      - /app/node_modules # evita conflictos de dependencias
    depends_on:
      - qp_backend
    networks:
      - qp_network  
    restart: unless-stopped

  # Loki
  loki:
    container_name: qp_loki
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - qp_network

  # Grafana
  grafana:
    image: grafana/grafana:10.4.2
    container_name: qp_grafana
    ports:
      - "3000:3000" # acceso desde el host
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASS}
    depends_on:
      - loki
    networks:
      - qp_network
    restart: unless-stopped

# 📦  Volúmenes persistentes
volumes:
  mongo_data:

# 🌐  Red interna compartida
networks:
  qp_network:
    driver: bridge
